.circleci/config.yml
CHANGELOG.md
README.md
package.json
rollup.config.js
src/converter.ts
src/error.ts
src/marp-cli.ts
src/templates.ts
src/templates/bare.pug
src/typings.d.ts
test/converter.ts
test/marp-cli.ts
tsconfig.json
yarn.lock

This PR will support converting Marp slide deck into PDF directly. We use a [headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) through [Puppeteer](https://github.com/GoogleChrome/puppeteer).
marp-cli recognizes `--pdf` option or `-o` option with `.pdf` extension.
```bash
npx @marp-team/marp-cli slide-deck.md --pdf
npx @marp-team/marp-cli slide-deck.md -o convert.pdf
```
We are using [puppeteer-core](https://www.npmjs.com/package/puppeteer-core) package to avoid installing a new Chromium to your computer, so the PDF conversion will require Chrome that is installed by user.
Fix yhatt/marp#50, yhatt/marp#164, and yhatt/marp#222.
> **For [yhatt/marp](https://github.com/yhatt/marp) user:** marp-cli is based on the new Marpit framework. You might have to update …

Convert slide deck into PDF with Puppeteer

---

CHANGELOG.md
src/converter.ts
src/marp-cli.ts
test/converter.ts

This PR will add `--html` option to enable or disable HTML tag.
For security reason, Both of Marpit and Marp Core have disabled HTML by default (In future we might allow several tags like `<br>` by whitelisting). CLI interface can allow HTML by user's operation.
```bash
marp markdown.md --html
marp markdown.md --html=true
marp markdown.md --html=false
```
For supporting Marpit based engine, we will set markdown-it's html option forcely.
To avoid confusing with an export type (HTML or PDF), we added option group about `Marp / Marpit Options` to the help message.

Add html option

---

CHANGELOG.md
src/config.ts
src/engine.ts
test/engine.ts
test/marp-cli.ts

When the `marp` command was installed in global, it might confuse by using a global command in a project that has already installed marp-core. The user-installed core would never use, and it will use bundled core in global when user not specify engine name.
This PR will support to resolve path for user-installed core by default.

Use user-installed marp-core by default

---

CHANGELOG.md
package.json
yarn.lock

This PR will update dependent package versions to latest version by `yarn upgrade(-interactive) --latest`. It has included the update of `@marp-team/marpit` and `@marp-team/marp-core`, that would resolves yhatt/marp#243.
We are going to publish new version as soon as if have confirmed the result of CI.

Upgrade dependent package versions to latest

---

.circleci/config.yml
.dockerignore
CHANGELOG.md
Dockerfile
README.md
src/converter.ts

This PR would add official Docker image in [`marpteam/marp-cli` at Docker Hub](https://hub.docker.com/r/marpteam/marp-cli/). It can convert Marp Markdown into HTML or PDF without installing node and Chrome/Chromium.
There are remaining issues as below, but currently we only have implemented basic feature.
- Create a light weight image by excluding chromium
- Support PDF conversion with several languages by including Noto fonts
In pre-release, we would have only `latest` tag created by automated build from `master` branch. We will be tagging by version from the first minor release (when todo on README.md are all done).
Related to yhatt/marp#232 and yhatt/marp#233.

Add official Docker image

---

CHANGELOG.md
src/templates/bare/bare.scss
src/templates/bespoke/bespoke.scss

The slide-deck outputted with bare template would not scaled-down correctly if you are opening it in Mac's Chrome. This problem had been a headache continued from marp-team/marpit#35 over 3 months.
We found a bit hacky workaround that use `transform` style. This PR would apply `transform: translateZ(0);` to SVG element of each template.
|Before|After|
|:---:|:---:|
|<img width="1508" alt="before" src="https://user-images.githubusercontent.com/3993388/45346774-2eac9280-b5e5-11e8-9d23-49457bb0a7c6.png">|<img width="1508" alt="after" src="https://user-images.githubusercontent.com/3993388/45346791-379d6400-b5e5-11e8-8bec-8e0d5c3f4a9b.png">|
> *APPENDIX:* It seems to be caused by the layout engine. Chrome has other problems that may be resolved by very similar workaround, e.g. …

Fix incorrect SVG scaling on Chrome

---

CHANGELOG.md
src/config.ts
src/converter.ts
src/marp-cli.ts
src/templates/index.ts
src/theme.ts
src/watcher.ts
test/_configs/custom-engine/marp.config.js
test/_configs/marpit/config.js
test/_configs/package-json/package.json
test/converter.ts
test/marp-cli.ts
test/theme.ts
test/watcher.ts

This PR will support auto-reload of user theme CSS specified by `--theme-set` option in watch mode.
After rendering Markdown to HTML, we track the change of used theme CSS. When you have updated observed CSS, an auto-reloading is triggered to markdowns that has used updated theme.
We have refactored the way of management user-created themes, using `ThemeSet` class.

Support auto-reload of user theme CSS in watch mode

---

CHANGELOG.md
package.json
src/config.ts
test/marp-cli.ts

User might think that `--theme` option may allow theme directory. But it returns not-friendly error when specify directory actually.
We have improved error message on passing directory to `--theme` option. It leads user to use `--theme-set` option.

Improve error message of theme option when passed directory

---

CHANGELOG.md
Dockerfile
src/converter.ts

This PR will add fonts to Docker image for internationalization.
In several languages, you may see fonts as [tofu] by converting PDF in Docker environment. In general, we recommend using Web fonts if you want to specify your favorite fonts in theme. But otherwise, we will use the added basic fonts.
We have added fonts that has [many native speakers]. In future we would accept pull requests about the other language.
|Before|After|
|:---:|:--:|
|![before](https://user-images.githubusercontent.com/3993388/45885436-68557880-bdf1-11e8-9533-6c196ed03509.png)|![after](https://user-images.githubusercontent.com/3993388/45885443-6d1a2c80-bdf1-11e8-80c5-b4b9412065af.png)|
Chinese hans and Japanese kanji have small differences of glyph. By default we use chinese fonts, but we can use Japanese fonts …

Add fonts to Docker image for internationalization

---

CHANGELOG.md
src/config.ts
src/marp-cli.ts
src/theme.ts
test/marp-cli.ts
test/theme.ts

This PR will change the behavior of `--input-dir` (`-I`) option to recognize theme CSS in specified directory.
One of the expected use case is that there is theme CSS next to Markdown.
```
slides
├── slide1.md
├── slide2.md
├── slide3.md
├── my-theme1.css
└── my-theme2.css
```
Currently we have to specify folder twice in input arguments (or `--input-dir` option) and `--theme-set` option if you want to use these. It is bit redundant.
```
marp ./slides --theme-set ./slides
```
So we'll find out theme CSS from specified directory if `--input-dir` option was defined. Internally the directory will be added to the array of theme set option.
Thus, you would be OK just to run together with `-I` option in this case.
```
marp -I ./slides
```
In current version, it would throw an error and fail …

Recognize theme CSS in input directory

---

CHANGELOG.md
package.json
yarn.lock

marp-team/marp-core has updated to v0.0.11 by reason of found out a regression of fitting header. Refer to marp-team/marp-core#37.

Upgrade marp-core to fix fitting header regression

---

CHANGELOG.md
package.json
src/config.ts
src/converter.ts
src/engine.ts
src/file.ts
src/server.ts
src/templates/index.ts
src/theme.ts
test/__mocks__/fs.ts
yarn.lock

This PR will use `util.promisify` to wrap callback-based funcs for converting to async functions
We had wrapped some functions manually. And now, we can recieve same results by simple definition provided from `util.promisify()`. We're using polyfill to support Node 6 environment.

Use util.promisify to wrap callback-based funcs

---

CHANGELOG.md
src/converter.ts

Marpit's inline SVG mode causes incorrect rendering of elements inside `<foreignObject>` in current Chrome, but it will be fixed by Chromium's BlinkGenPropertyTrees. This PR will add `--enable-blink-gen-property-trees` option as the default argument to convert PDF.
It could render slide deck with the correct layout more certainly.
See: https://bugs.chromium.org/p/chromium/issues/detail?id=467484

Enable chromium --enable-blink-gen-property-trees argument

---

CHANGELOG.md
src/config.ts

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer), `defer` attribute of inline `<script>` element would have no effect.
Marp CLI has defined `defer` attr to inline script for browser context. So we can remove this attribute safely.

Remove defer attribute from inline script tag

---

CHANGELOG.md
src/converter.ts
test/marp-cli.ts

`new Buffer()` has already marked as deprecated by security reason, and Node 10 outputs warning about deprecation.
https://nodesource.com/blog/understanding-the-buffer-deprecation-in-node-js-10/
We must use `Buffer.from()` instead of deprecated constructor.

Use Buffer.from() instead of deprecated constructor

---

CHANGELOG.md
package.json
rollup.config.js
src/marp-cli.ts
src/server.ts
src/server/assets/icon-directory.svg
src/server/assets/icon-file.svg
src/server/assets/icon-marp.svg
src/server/index.pug
src/server/index.scss
test/server.ts
yarn.lock

Current server mode is bit difficult to use because it requires to access file URL manually. This PR will provide served file list as [the directory index](https://en.wikipedia.org/wiki/Webserver_directory_index). By accessing http://localhost:8080/, marp-cli shows the list of served markdown files.
Currently CLI provides the super-simple file list by using `serve-index`, but we can improve by our Pug template and SCSS.
I'm going to add a checkbox whether to toggle showing served static files (non-markdown files) in another PR.
The improved server mode no longer recognize the conversion type option like `--pdf`. We always serve the deck as HTML by default.
Instead, we recognize `?pdf` query parameter in accessed URL. You can execute the on-demand PDF conversion while serving HTML. The …

Improved server mode

---

CHANGELOG.md
src/converter.ts
test/_configs/custom-engine/anonymous.js
test/marp-cli.ts

This PR will support the functional engine by passing `engine` option through JS configuration. It would become to customize Marp or Marpit engine easily by a lot of markdown-it plugins.
For example, you can use `==mark==` syntax by [markdown-it-mark](https://www.npmjs.com/package/markdown-it-mark). It will turn into `<mark>mark</mark>`.
```javascript
// marp.config.js
const { Marp } = require('@marp-team/marp-core')
const markdownItMark = require('markdown-it-mark')
module.exports = {
engine: opts => {
const core = new Marp(opts)
core.markdown.use(markdownItMark)
return core
},
}
```

Support functional engine

---

CHANGELOG.md
src/__mocks__/engine.ts
src/config.ts
src/engine.ts
src/marp-cli.ts
src/version.ts
test/_configs/custom-engine/custom-engine.js
test/_configs/custom-engine/file.js
test/_configs/custom-engine/marp.config.js
test/_configs/custom-engine/package.json
test/engine.ts
test/marp-cli.ts

Improve `--version` (`-v`) option to output the version of engine based on the current configuration / arguments.
```
$ marp -v
@marp-team/marp-cli v0.0.14 (/w bundled @marp-team/marp-core v0.2.1)
```
```
$ npm install @marp-team/marpit --save-dev
$ marp -v --engine @marp-team/marpit
@marp-team/marp-cli v0.0.14 (/w customized engine in @marp-team/marpit v0.3.3)
```
```
$ marp -v --engine ./your-engine.js
@marp-team/marp-cli v0.0.14 (/w customized engine in your-project v1.0.0)
```
```
$ npm install @marp-team/marp-core --save-dev
$ echo "const { Marp } = require('@marp-team/marp-core'); module.exports={engine: opts => new Marp(opts)}" > conf.js
$ marp -v -c ./conf.js
@marp-team/marp-cli v0.0.14 (/w customized engine)
```

Output the configured engine in version option

---

CHANGELOG.md
package.json
src/__mocks__/preview.ts
src/config.ts
src/converter.ts
src/marp-cli.ts
src/preview.ts
src/templates/bespoke/bespoke.scss
test/marp-cli.ts
test/preview.ts
yarn.lock

Support an experimental `--preview` option to open a preview window provided by [Carlo](https://github.com/GoogleChromeLabs/carlo). Marp CLI can open a mini window to show a preview of editing Markdown by using Chrome instance.
If you turned on `--preview` option, `--watch` option is enabled automatically too. It would provide a better experience while writing the Marp presentation in your favorite editor as like as [Deckset](https://www.deckset.com/features/).
Of course you can use it to the actual presentation by maximize window.
It is marked as *an experimental support* because of some restrictions.
- Marp CLI is still supporting Node v6, but Carlo is not supported, requires Node >= 7. You can not use `--preview` option if Marp CLI is running in Node 6.
- `--preview` is available only …

[Experimental] Support opening preview window provided by Carlo

---

.gitignore
CHANGELOG.md
src/file.ts
src/server.ts
src/server/index.pug
src/server/index.scss
src/theme.ts
test/server.ts

In the case using the custom engine or functional engine implemented in #42, Marp CLI will try globbing `node_modules` when specified a project directory through `--input-dir` or `--server` option.
So `--server` option would output ugly logs 🤮
```
$ marp --server ~/Documents/marp-cli
[  WARN ] Cannot register theme CSS: ./Documents/marp-cli/node_modules/highlight.js/styles/a11y-dark.css (Marpit theme CSS requires @theme meta.)
[  WARN ] Cannot register theme CSS: ./Documents/marp-cli/node_modules/highlight.js/styles/a11y-light.css (Marpit theme CSS requires @theme meta.)
[  WARN ] Cannot register theme CSS: ./Documents/marp-cli/node_modules/highlight.js/styles/agate.css (Marpit theme CSS requires @theme meta.)
[  WARN ] Cannot register theme CSS: …
```

Ignore node_modules in globbing

---

CHANGELOG.md
src/marp-cli.ts
test/marp-cli.ts

Until merging #47, We had not provided shorthand option for preview because it was not supported regular conversion. And now, the preview option is working in regular conversion. So we add `-p` alias to preview option.

Add -p alias to --preview option

---

CHANGELOG.md
package.json
src/templates/bare/bare.pug
src/templates/bespoke/bespoke.pug
src/templates/bespoke/fullscreen.ts
src/templates/index.ts
yarn.lock

By [long standing bug](https://bugs.webkit.org/show_bug.cgi?id=23113), the outputted HTML could not present slide deck in WebKit based browser. (Safari, iOS Chrome, iOS Firefox, etc..)
But recently we have created [@marp-team/marpit-svg-polyfill](https://github.com/marp-team/marpit-svg-polyfill) to fix the unstable rendering. It includes polyfill for WebKit based browser, and its applied slide deck can present correctly even if in WebKit.
This PR will improve WebKit browser support. It includes:
- Update Marpit framework and Marp Core to apply polyfill
- Use polyfill in bespoke template when engine has not provided browser JS (e.g. Marpit)

Improve WebKit browser support

---

src/converter.ts

- there is a problem that PDF is not generated in Chrome Canary.
- it's generate a blank page.
- change output URL from plain-text to base64
```
Chrome Version: 73.0.3683.0 (Official Build) canary (64 bit)
```

convertFileToPDF: Use base64 string as URL

---

CHANGELOG.md
src/preview.ts

In macOS, Carlo's workaround for Windows implemented in #47 would cause failing test.
I updated to execute workaround only in Windows.

Fix failed test in other platform by Windows workaround for Carlo

---

src/templates/bespoke/fullscreen.ts
src/templates/bespoke/osc.ts
test/__mocks__/screenfull.ts
test/templates/bespoke.ts

Fullscreen button on bespoke template's OSD is sometimes not reflected the correct state. When the fullscreen was toggled by browser native feature, the fullscreen icon would not change.
We are improved handling the fullscreen icon by using `fullscreenchange` browser event through `screenfull` helper module (`screenfull.onchange()`), not using our custom event.

Reflect the correct fullscreen icon in bespoke template

---

CHANGELOG.md
README.md
package.json
src/cli.ts
src/config.ts
src/converter.ts
src/engine/meta-plugin.ts
src/marp-cli.ts
src/templates/bare/bare.pug
src/templates/bespoke/bespoke.pug
src/templates/index.ts
src/templates/layout.pug
test/_configs/custom-engine/custom-engine.js
test/_transformers/pug.js
test/converter.ts
test/marp-cli.ts
test/server.ts
yarn.lock

This PR adds the support to recognize HTML metadata from Markdown front-matter, powered by custom directives support in [Marpit v0.7.0](https://github.com/marp-team/marpit/releases/v0.7.0).
```markdown
---
title: Slide deck
description: A beautiful slide deck created by Marp
url: https://marp.app/example
image: https://marp.app/ogp.jpg
theme: default
---
```
Marp CLI will recognize 4 new global directives.
- `title`: Setting title for `<title>` tag and OGP title.
- `description`: Setting description for `<meta name="description">` and OGP description.
- `url`: Setting canonical URL for `<link rel="canonical">` and OGP URL.
- `image`: Setting OGP image URL. [Twitter's Summary Card will be used the large image](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary …

Support setting HTML metadata

---

.circleci/config.yml
CHANGELOG.md
package.json
src/engine/meta-plugin.ts
yarn.lock

Upgrade dependent packages to latest version by using ~~`yarn upgrade --latest`~~ `yarn upgrade-interactive --latest`.
This PR is included the update of [Marpit v0.7.1](https://github.com/marp-team/marpit/releases/tag/v0.7.1) and [Marp Core v0.6.0](https://github.com/marp-team/marp-core/releases/tag/v0.6.0). It has no other changes except Prettier.

Update dependent packages to latest (Marpit v0.7.1 and Marp Core v0.6.0)

---

CHANGELOG.md
Dockerfile

Chromium versions are not matched between alpine build and supported in Puppeteer. We should downgrade Puppeteer to Chrome 71 supported version in Docker image.
Fix #73.

Fix hanging PDF conversion within Docker image

---

.circleci/config.yml
CHANGELOG.md
package.json
src/converter.ts
yarn.lock

The latest Marp CLI could not have tested with current stable Chrome (73) because of GoogleChrome/puppeteer#3774.
A worthy workaround has reported to that thread, so we will update workaround for this issue to the reported way. It will get more robust test based on the real use case.
> NOTE: Marp Core is updated to v0.7.1 to fix audit report. The other dependencies would update in another PR.

Update a workaround for the stable chrome's crash in docker image

---

CHANGELOG.md
README.md
package.json
src/templates/bespoke/bespoke.scss
src/templates/bespoke/bespoke.ts
src/templates/bespoke/fragments.ts
src/templates/bespoke/navigation.ts
src/templates/bespoke/osc.ts
test/templates/bespoke.ts
yarn.lock

Fragmented list is a new feature of Marpit v0.9.0. It's easy to write the list to be appeared one-by-one. Just use `*` bullet and `1)` bracket style index.
This PR supports fragmented list parsed by Marpit v0.9.0 in bespoke template. Our implementation is based on bespoke-bullet plugin, but we have extra feature for jumping to the beginning page and the ending page with considering fragments by hitting <kbd>Home</kbd> and <kbd>End</kbd> key.
Currently we are not using the stored value in `data-marpit-fragment` parsed by Marpit. Fragments plugin will only recognize whether it has data attribute.
If you familiar to reveal.js, you can use `<div data-marpit-fragment>` HTML element as a fragmented block with `--html` option.
- Deck: https://gistcdn.githack.com/yhatt/efc4ba8999274112072f97c7d48d …

Support fragmented list from Marpit v0.9.0

---

CHANGELOG.md
src/converter.ts
test/converter.ts

By default, Marp Core allows whitelisted HTML element `<br>`. But Marp CLI has always overridden Marp Core's html option wrongly.
We have fixed the converter to override only if defined html option.

Override engine html option only if defined in CLI

---

.circleci/config.yml
CHANGELOG.md
README.md

Automate GitHub release by using common script added to entrance repository. (marp-team/marp#15).
Essentialy the purpose is as same as marp-team/marpit#161 and marp-team/marp-core#87, but Marp CLI has standalone binaries (#87) as assets on GitHub release.
- I had a bit change to common script in https://github.com/marp-team/marp/commit/1ea47d766cdcceeb8c9f84499c677e49696ac973: Outputs ID number for GitHub release API.
- The outputted ID uses to upload assets in CircleCI job.
I've tested scripts partially, but nobody knows whether it really works till trying. (CircleCI cannot test the whole of workflow on local environment)
- Update README.md

Automate GitHub release with uploading standalone binary assets

---

.circleci/config.yml
CHANGELOG.md

I've confirmed Marp CLI is also working on Node 12 (Erbium) now. As same as https://github.com/marp-team/marpit/pull/160, we added the test environment of CircleCI with Node 12.

Test with Node 12 (Erbium)

---

.gitignore
.prettierignore
CHANGELOG.md
package.json

Update `package.json` to add main entry point and type definitions. 
Basically Marp CLI has not provided internal API for Node because we want to focus a behavior in the scope of CLI/CUI. However, an exported function from entry point is useful as a minimum interface to use CLI via Node.
```javascript
const marp = require('@marp-team/marp-cli')
(async () => {
const exitCode = await marp(['marp.md', '-o', 'marp.html'])
if (exitCode === 0) {
// succeeded
} else {
// error
}
})()
```
This function may be used in Marp for VS Code: https://github.com/marp-team/marp-vscode/issues/4

Add main entry point and type definitions

---

CHANGELOG.md
src/marp-cli.ts
test/marp-cli.ts

Add `--stdin` boolean option for enable or disable reading Markdown from stdin (`true` by default). By setting `--stdin=false` or `--no-stdin`, Marp CLI won't read content from stdin. It allows to avoid hang up while reading stdin in several environments.
`--stdin` is a hidden option because reading stdin is an expected behavior for most users using CLI. User can see help with `--show-hidden` if necessary. (It's a built-in option of yargs)
```
$ marp --help --show-hidden
...
Basic Options:
...
--stdin            Read Markdown from stdin     [boolean] [default: true]
```
`--no-stdin` helps to resolve the problem for Now deploy environment and Marp for VS Code. Close #93.

Add hidden stdin option

---

CHANGELOG.md
jest.setup.js
package.json
src/cli.ts
src/converter.ts
src/file.ts
src/marp-cli.ts
test/__mocks__/wrap-ansi.ts
test/converter.ts
test/marp-cli.ts
yarn.lock

Now Marp CLI outputs warning if failed the request of file scheme. (powered by Puppeteer's `requestfailed` event)
User can see this warning when using local files in Markdown conversion to PDF and images. It would help user to notice requiring uploaded assets, or lacked `--allow-local-files` option to render local files.
It requires the update of `href` attr of `base` tag: Add `file:` scheme, to fallback a relative path in `data:` scheme HTML to `file:` scheme and catch request errors by Puppeteer correctly.
Fixes #84.

Output warning if detected blocking local resources while rendering by Chrome

---

.circleci/config.yml
CHANGELOG.md

Sometime CircleCI fails by returning error in `yarn audit` with 503 status code even if test has not any problems.
```
#!/bin/bash -eo pipefail
yarn audit
yarn audit v1.13.0
/opt/yarn-v1.13.0/lib/cli.js:66237
throw new (_errors || _load_errors()).ResponseError(_this3.reporter.lang('requestFailed', description), res.statusCode);
^
Error: Request failed "503 Service Unavailable"
at ResponseError.ExtendableBuiltin (/opt/yarn-v1.13.0/lib/cli.js:702:66)
at new ResponseError (/opt/yarn-v1.13.0/lib/cli.js:808:124)
at Request.params.callback [as _callback] (/opt/yarn-v1.13.0/lib/cli.js:66237:19)
at Request.self.callback (/opt/yarn-v1.13.0/lib/cli.js:129397:22)
at Request.emit (events.js:189:13)
at Request.<anonymous> (/opt/yarn-v1.13.0/lib/cli.js:130369:10)
at Request.emit (events.js:189:13)
at …
```

Run yarn audit only in beginning of CircleCI

---

src/server.ts
test/__mocks__/express.ts
test/server.ts

Fixed to handler httpServer start up error.
For example, current marp-cli ignores EADDRINUSE error as below:
```
% marp --html --server .
[  INFO ] [Server mode] Start server listened at http://localhost:8080/ ...
```
**Changes**: 
- Properly handle `'error'` event of node.js httpServer
- Fixed "Unhandled promise rejection" problem on server startup error
- Handle `EADDRINUSE` to show user friendly message

Fix httpServer error handling.

---

CHANGELOG.md
README.md
src/version.ts
test/marp-cli.ts

Marp CLI prefers user-installed Marp Core instead of bundled version. However, npm (or yarn) sometimes merge two patch versions. In this case, `marp --version` cannot detect user-installed core and may show an incorrect version.
So we've improved `--version` (`-v`) command: Outputs `w/ user-installed @marp-team/marp-core vX.X.X` when a resolved Marp Core has unexpected version against bundled.

Improve version output when using user-installed Marp Core

---

CHANGELOG.md
package.json
yarn.lock

This PR will upgrade ~~dependent package versions~~ Marp Core to the latest version by `yarn upgrade --latest`.
It only includes the update of Marp Core v0.10.2 and can reduce file size of the converted HTML.
We are going to publish new patch version as soon as if have confirmed the result of CI.

Upgrade Marp Core to v0.10.2

---

CHANGELOG.md
src/marp-cli.ts
src/preview.ts
src/server.ts
test/server.ts

I've refactored `Server` class by extending `(Typed)EventEmitter` to improve error handling while converting Markdown.
- A constructor option `onConverted` is replaced to `convert` event provided by `EventEmitter`.
- When raising an error while converting Markdown...
- Returns 503 error with raised error message.
- Emits `error` event with error instance. Marp CLI uses this to output error message to console.

Refactor Server class to handle error while converting

---

CHANGELOG.md
demo/demo.md
demo/index.md

- Update demo slide Markdown from the original content to the content used in screencast.
- Rename filename from `demo.md` to `index.md` to serve slide by default.

Update demo slide to Markdown used in screencast

---

CHANGELOG.md
src/marp-cli.ts

By closing watcher and notifier in the `finally` block, a hot reload feature via `--watch` (`-w`) was not working since v0.10.1. 😭

Fix up not working watch mode

---

CHANGELOG.md
src/config.ts
src/file.ts
test/marp-cli.ts
test/theme.ts

Resolves #95.
I've updated `File.find()` to collect passed files that refers to a real file path at first. After than, remaining glob pathes will pass to globby.

Process glob-like path that refers to a real file correctly

---

CHANGELOG.md
src/config.ts
src/marp-cli.ts

To match the type of configuration object defined in yargs, `--bespoke-osc` and `--bespoke-progress` option arguments were renamed to using dot notation: `--bespoke.osc` and `--bespoke.progress`.
Hyphenated options still can use but they will output warnings.

Rename bespoke option arguments using dot notation

---

CHANGELOG.md
src/templates/watch/watch.ts
test/templates/watch.ts

In watching the change of files by `--watch` and `--server`, generated HTMLs cannot recover WebSocket connection when disconnected from server.
This PR adds the logic trying to recover connection if disconnected from WebSocket server. It's useful for tracking change of engine JS through using additional tools such as `nodemon`.

Reconnect to file watcher when disconnected from WebSocket server

---

CHANGELOG.md
package.json
src/file.ts
yarn.lock

I'm trying to resolve #133.
`url.pathToFileURL` cannot use in Node < v10.12.0 so file scheme URI would be resolved manually. A problem is that its logic is using `path.posix.resolve()`. It would be returned incorrect path in Windows.
We've fixed it by using `file-url` module. Marp for VS Code's built-in Node is v10.11.0 so it may resolve an edge case like reported in https://github.com/marp-team/marp-vscode/issues/64.

Fix fallback of File#absoluteFileScheme for old Node

---

.gitpod.yml
CHANGELOG.md
src/watcher.ts
test/converter.ts
test/templates/watch.ts
test/watcher.ts

Resolves #135.
Now `portfinder` is no longer prevented using port > 40000, but a reason why should prevent using these port is explained clearly in https://github.com/http-party/node-portfinder/pull/82#issuecomment-520199847.
A new port number 37717 is just a meaingless prime number. ;)

Change port number for file watcher from 52000 to 37717

---

CHANGELOG.md
marp-cli.js
package.json
yarn.lock

Make CLI be faster by adding `v8-compile-cache` that attaches the require hook for using V8 code cache.
Benchmark of `time ./marp-cli.js` in my environments shows not dramatic but steady x1.15 speed up. (Use average time of 10 executions)
|`real`|Mac|Win|
|:---:|:---|:---|
|`master`|0.671s|0.960s|
|`v8-compile-cache`|0.585s (x1.15)|0.843s (x1.14)|

Add v8-compile-cache to make faster startup

---

.github/workflows/github-release.yml
.github/workflows/test-win.yml
CHANGELOG.md

Workflows defined by GitHub Actions will upload the coverage result and packaged binaries to artifacts as same as CircleCI.

Upload artifacts within GitHub Actions

---

CHANGELOG.md
Dockerfile

#139 makes CLI be faster but Docker image has not prepared V8 compile cache. This PR will run Marp CLI once while building Docker image and create v8 precompiled cache.
It has about x1.1 faster startup.

Precompile v8 cache while building Docker image

---

CHANGELOG.md
src/templates/bespoke/bespoke.ts
src/templates/bespoke/state.ts
src/templates/bespoke/utils.ts
test/templates/bespoke.ts

We've renewed Bespoke.js hash plugin to "State plugin". It holds the index of shown fragment on to `f` query parameter if the current state of slide is in the progress of fragments.
User can show the middle of fragment animation by accessing URL that has `f` query parameter.
We are planning to make the best use of this feature in next slide preview in presenter view. (#142)

Hold the progress state of fragments on to URL query parameter

---

CHANGELOG.md
src/templates/bespoke/bespoke.scss
src/templates/bespoke/bespoke.ts
src/templates/bespoke/load.ts
test/templates/bespoke.ts

Fix vanished Marp Core's auto-fitting elements by keeping the background rendering for calculating the size of them.
Resolves #153.

Add bespoke load plugin

---

CHANGELOG.md
src/templates/bespoke/state.ts

Safari may throw SecurityError by replacing state 100 times per 30 seconds. Wrapping in try-catch is important for doing remained processes correctly.
Resolves #158.

Wrap bespoke state plugin's state updation in try-catch

---

CHANGELOG.md
package.json
src/config.ts
src/converter.ts
src/engine.ts
src/templates/index.ts
src/templates/layout.pug
src/version.ts
test/converter.ts
test/engine.ts
test/marp-cli.ts
yarn.lock

An updated Marp Core v0.14.0 has injected helper script for browser automatically. Now Marp Core's rendering works well in the customized engine (#168).
By this change, the detection of `marpBrowser` from `package.json` is no longer required. I've removed the logic to inject helper script by Marp CLI.

Remove the detection of helper script from resolved engine

---

CHANGELOG.md
src/converter.ts
src/preview.ts
src/utils/find-chrome.ts
test/preview.ts
test/watcher.ts

Unified the resolution algorithm of Chrome to the logic based on `chrome-launcher`, that has already supported macOS Catalina. By this change, `CHROME_PATH` env will work in preview mode too.
Fix #170.

Support preview mode in macOS Catalina

---

CHANGELOG.md
Dockerfile

https://app.circleci.com/jobs/github/marp-team/marp-cli/2528/parallel-runs/0/steps/0-103
```
$ chromium-browser --version
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found
```
Chromium on Alpine Linux now requires `libstdc++`.

Update Dockerfile to work Chromium correctly

---

CHANGELOG.md
package.json
src/templates/bespoke/bespoke.scss
src/templates/bespoke/bespoke.ts
src/templates/bespoke/interactive.ts
src/templates/bespoke/osc.ts
test/templates/bespoke.ts
yarn.lock

We've added interactive plugin for bespoke, to improve event handling about keys for navigation. We had used [`bespoke-forms`](https://github.com/bespokejs/bespoke-forms) but it does not support recent elements such as `<button>`, `<video>` and `<audio>`.
And we've improved focus handling on OSC. The overlay control is not assumed to control with keyboard, so we are going to remove focus ring through `blur()`.
Resolves #156.

Add bespoke interactive plugin to improve event handling

---

CHANGELOG.md
src/converter.ts

Marp CLI does not render local file assets in WSL environment even if `--allow-local-files` option is enabled.
We are using Puppeteer to convert Markdown into PDF, PPTX, and images through *Windows Chrome*, so tmp file has to resolve base path into WSL.

Fix failing --allow-local-files option on WSL environment

---

.github/workflows/test-win.yml
CHANGELOG.md
README.md

GitHub Actions is now generally available and with caching support by [actions/cache](https://github.com/actions/cache). We've set up cache for `node_modules` in test on Windows.

Setup cache, badge, and skip tag support for GitHub Actions

---

CHANGELOG.md
README.md

Shields.io now supports a badge for GitHub Actions workflow.

Replace different style badge for GitHub Actions

---

src/converter.ts

Thank you for creating this great CLI.
Currently, when `allowLocalFiles` is set to `true` and some local files are missing, marp-cli issues `Marp CLI has detected accessing to local file. That is blocked by security reason. Instead we recommend using assets uploaded to online.` warning. This message is confusing because users are told to set `allowLocalFiles` to true even though they've already done so.
Adding new error message that indicates some local files are missing would be very helpful. In this PR, I propose the error message `Marp CLI has detected accessing to local file that does not exist.`

Add missing local file error message

---

CHANGELOG.md
src/converter.ts
src/file.ts
src/utils/puppeteer.ts
test/converter.ts

Resolve #201 and marp-team/marp-vscode#94. See details in https://github.com/marp-team/marp-cli/issues/201#issuecomment-586725940.
> we recognized the Snapd Chromium cannot access from the sandbox container to user-land `/tmp/`, due to [strict snap confinement](https://snapcraft.io/docs/snap-confinement). Snapd Chromium only allows [reading visible files from `$HOME`](https://snapcraft.io/docs/home-interface).
> 
> Marp CLI should create visible tmp file into `$HOME` when the resolved Chromium path starts with `/snap`.

Create tmpfile to home directory when detected Snapd Chromium

---

CHANGELOG.md
package.json
src/converter.ts
test/converter.ts
yarn.lock

We were used `@marp-team/pptx` to reduce fat dependencies in PptxGenJs v2. And now, [PptxGenJS v3](https://gitbrent.github.io/PptxGenJS/) has improved build. So we will get rid of `@marp-team/pptx` dependency and use PptxGenJs v3.
PowerPoint creation logic also has refactored to make a single master slide rather than mater slides per pages. Fix #166.

Use PptxGenJS v3 instead of @marp-team/pptx

---

CHANGELOG.md
README.md
src/templates/bespoke/osc.ts
src/templates/bespoke/presenter/normal-view.ts
src/templates/bespoke/sync.ts
src/templates/bespoke/utils.ts
test/templates/bespoke.ts

We received the report about not working the whole of bespoke template in the browser that has restricted using `localStorage`. This PR will make some bespoke plugins robust against errors thrown by `localStorage`.
- Sync plugin manipulates `localStorage` through the robust storage utility object. The presentation does not stop working by thrown error but sync logic may not be able to use in some rarely cases.
- The plugin depended on sync plugin will disable when using `localStorage` is restricted. It's relevant to presenter plugin and OSC plugin (presenter button).
Resolves #207.

Make bespoke plugin robust against storage errors

---

CHANGELOG.md
src/templates/bespoke/touch.ts

Lighthouse is pointing out to [use passive event listener for improving scroll performance with touch](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners). This PR adds `{ passive: true }` to touch event listeners that does never call `e.preventDefault()`.

Use passive event listener as much as possible

---

src/utils/puppeteer.ts

Marp CLI had overridden the argument for disabling BGPT, to enable BGPT forcibly (Enabling BGPT prevents glitched rendering of slide: #78). However, [Puppeteer >= v2.1.0 does no longer disable `BlinkGenPropertyTrees`](https://github.com/puppeteer/puppeteer/pull/5159).
I've refactored `src/utils/puppeteer.ts` to follow the default argument.

Refactor Puppeteer arguments

---

CHANGELOG.md
Dockerfile

Puppeteer does not provide `chrome-80` tag so building Docker image was failed. If the compatible tag is not found, we will ignore install step of `puppeteer-core` in Dockerfile.

Ignore installing step of puppeteer-core in Dockerfile if the compatible tag is not found

---

src/server/index.pug

Fixed URLs serving index files (`index.md`, `PITCHME.md`) in server mode.
Write presentation files in directories like below:
- `serverRoot/files/index.md` : markdown file for Marp
- `serverRoot/files/image.png` : image file, used in index.md as `![](image.png)`
And run marp-cli as server mode like `marp --server serverRoot/`.
Then `http://localhost:8080/` shows files and directories in `serverRoot` by `serve-index`.
In the above settings, a link on that page is `http://localhost:8080/files`.
When access to that, `serverRoot/files/index.md` is converted and shown in a browser, but `serverRoot/files/image.png` is not shown in the presentation because the presentation address is `/files` and `![](image.png)` is linked to `/image.png`, not `/files/image.png`.
When access to …

Fix serving index files

---

CHANGELOG.md
package.json
yarn.lock

I met a lot of bugs preventing development in `@rollup/plugin-typescript` v4:
- Watch mode will degrade performance and finally crash by out of memory (https://github.com/rollup/plugins/issues/322)
- Invalid type in watch mode will make failing the whole of process (https://github.com/rollup/plugins/issues/258)
- We should set `noEmitError: false` manually.
- TS incremental build throws an error in second build (https://github.com/rollup/plugins/issues/249)
We will temporarily downgrade into v3 to make development going smoothly.

Revert @rollup/plugin-typescript to v3

---

CHANGELOG.md
src/file.ts
test/marp-cli.ts
test/server.ts

Similar to #117 but it's for the directory path. Fix #227.

Fix path resolution of the directory whose name included glob special chars

---

CHANGELOG.md
README.md
jest.setup.js
package.json
src/marp-cli.ts
src/preview.ts
test/marp-cli.ts
test/preview.ts
yarn.lock

Our decision of experimental `--preview` deprecation is backed out! `Preview` class has reimplemented with `puppeteer-core` and got rid of unmaintained `carlo`. `--preview` (`-p`) option should work as before.
The first our implementation of preview window is *still experimental*.
Closes #211.

Recover experimental preview window

---

CHANGELOG.md
src/converter.ts
src/preview.ts
src/utils/puppeteer.ts

Improved Puppetter utility based on several reports.
- Remove unnecessarry `async`/`await` keyword from `generatePuppeteerLaunchArgs()`.
- Throw `CLIError` with helpful message if the executable Chrome path cannot find out. (#220)
- Add escape-hatch for policy-applied Chrome Windows. (#231)
- Running `SET CHROME_ENABLE_EXTENSIONS=1` before executing Marp CLI can enable extensions while converting Markdown.
- Because of leading insecure conversion, we don't want to enable extensions by default if possible. It may break and leak the content of slide deck.
Closes #220. #231 needs more reports about this change.

Improve Puppetter utility based on several reports

---

CHANGELOG.md
src/templates/bespoke/classes.ts
src/templates/bespoke/inactive.ts
src/templates/bespoke/osc.ts
test/templates/bespoke.ts

Screen-reader does not follow the hidden state of some slide pages and on-screen controller in the exported HTML with `bespoke` template.
To improve a11y, we've updated some bespoke plugins to control `aria-hidden` attribute in some elements that are actually not hidden. I've confirmed that a11y was improved, by the accessibility inspector in Firefox developer tools.
Fixed #236.

Control aria-hidden attribute properly in bespoke template

---

CHANGELOG.md
src/templates/bespoke/bespoke.ts
src/templates/bespoke/wake-lock.ts
test/templates/bespoke.ts

Enable Screen Wake Lock API while opening presentation HTML. Resolves #239.
The current stable Chrome 84 has implemented Screen Wake Lock API. We can prevent turning off the screen while presenting exported HTML. I've confirmed it would work with local files too.

Add bespoke wake-lock plugin

---

.circleci/config.yml
.github/workflows/test-win.yml
CHANGELOG.md

We've started running test against Node 14 on CI, to support LTS candidate Node.js. Probably no changes for existing codes would require.

Test against Node 14

---

.github/dependabot.yml
CHANGELOG.md

This PR sets up GitHub Dependabot for marp-team packages as same as marp-team/marp-core#172.
Marp team is working to update dependencies regularly.
To save the time for routine work, we've set up GitHub Dependabot to update packages provided by @marp-team automatically.
Notice that the auto-update for external packages is not setting up. These still are going to update manually because may met some breaking changes.
> We have auto-update setting for GitHub Actions too, but it would not open PR because Dependabot forces specific version against the best practice of GitHub Actions. Setting loose version always can use the latest major version with no updating.

Set up GitHub Dependabot for marp-team packages

---

CHANGELOG.md
scripts/pack.js

While migrating to ESLint in #250, there was wrong replacement in the permission flag: Octal `0755` to decimal `755`.
`0755` is invalid number in the strict mode of JS, so we must use `0o755` instead.
Closes #256.

Fix invalid permission flag in package script

---

package.json
yarn.lock

After updating codecov-node to v3.7.1, we have met unexpected decrease in coverage.
https://codecov.io/gh/marp-team/marp-cli/commits
We should report this to Codecov. Until to be fixed, we will have to stick into v3.7.0 for getting better looking in badge.

Revert codecov-node to v3.7.0

---

CHANGELOG.md
src/utils/puppeteer.ts

Recently we met flaky test results again.
This PR sets `puppeteer.launch({ pipe: true })` to get more reliability of connection to Chrome by Puppeteer. `pipe: true` makes connection to Chrome process through process pipe instead of WebSocket, so we could expect decrease of flaky test results caused by unstable network on GitHub Actions environment.

Connect to Chrome via pipe rather than WebSocket

---

CHANGELOG.md
README.md
marp-cli.js
package.json
rollup.config.js
src/config.ts
src/engine.ts
src/error.ts
src/index.ts
src/marp-cli.ts
src/preview.ts
src/server.ts
src/utils/puppeteer.ts
test/__mocks__/express.ts
test/__mocks__/get-stdin.ts
test/index.ts
test/marp-cli.ts

The undocumented Marp CLI's API interface, that is used in Marp for VS Code, is hard to use by several reason:
- It does never respond whenever there is not added `--no-stdin` argument manually, and it is not documented too.
- `CLIError` has not thrown because it would be catched to display error into users. Developer has to rely to the exit code `0` or `1` that has limited informations.
By these reasons, Marp for VS Code often shows helpless error `Marp CLI throwed unexpected error with exit code 1`. By googling Marp for VS Code that message shows as related search keyword. :sob:
So I've improved API interface, to throw any kind of errors that includes `CLIError`. In addition, some `CLIError`s have discriminable exit code.
The default `stdin` option will change from running which …

Make public improved API interface for Node.js

---

CHANGELOG.md
src/utils/puppeteer.ts

In WSL environment, Puppeteer cannot connect into Windows Chrome through the pipe. I've disabled pipe when running Puppeteer on WSL.
This PR also includes refactoring for handling WSL.
Please be aware Marp CLI over WSL 2 is still not working. Puppeteer does not have a workaround for WSL 2. We have the basic code to detect WSL 2 in the future, but it is also not shipped.

Disable pipe for Puppeteer when running on WSL

---

src/utils/puppeteer.ts

Add `--export-tagged-pdf` option as the default option of Puppeteer to create PDF with improved accessibility.
Chromium team announced upcoming Chrome is going to be able to make tagged PDF.
https://blog.chromium.org/2020/07/using-chrome-to-generate-more.html
Puppeteer had tried to make `--export-tagged-pdf` as the default option since Jan at https://github.com/puppeteer/puppeteer/pull/5337. However, currently it's not yet added. By adding the option in Marp CLI, users will benefit of this in early.
Marp CLI have recieved a feedback by users who uses screen reader in #236. So this is important to keep continuous improvements for optically challenged users.
In addition, the added meta data may improve the quality of editable PPTX converted from PDF by third-party tools. Just Marp CLI …

Improve PDF accessibility by enabling --export-tagged-pdf Chromium option

---

README.md

Marp CLI standalone binaries are no longer experimental!
When released standalone binaries the first time, we marked them as experimental because we were afraid of some harmfuls from [`pkg`'s snapshot filesystem](https://github.com/vercel/pkg#snapshot-filesystem). But we have not recieved reports about the regression caused by pkg while a long time, so we can consider no bugs in experimental binaries.
We've re-organized documentation for the standalone binary.

Mark standalone binary as stable

---

src/config.ts
src/marp-cli.ts
test/marp-cli.ts

When Marp CLI installed in the local Node.js project, sometimes user may want to ignore a project-wide configuration file.
In this PR we will handle a negated  `--config-file` option. We won't look up a configuration file through cosmiconfig if passed `--no-config-file` option.
We also added an `--config` alias to `--config-file` option, for compatibllity with some CLI tools. It means that negated `--no-config-file` and `--no-config` will work as expected too.

Handle --no-config-file option to prevent looking up for a configuration file

---

README.md

The server option in the readme now documents the PORT environment variable to change the server port number.

Add port number instructions in readme for server option

---

CHANGELOG.md
src/converter.ts
src/file.ts

This PR includes these bugfixes:
- We've missed a breaking change in the bumped `tmp` dependency (https://github.com/marp-team/marp-cli/pull/229#commitcomment-42183269) so I fixed the logic for making tmpfile in `--allow-local-files` option.
- Recently Snapd Chromium is prepared the shebang script in `/usr/bin/chromium-browser`. `chrome-launcher` will detect this so we can't detect Snapd Chromium from the executable path. We may still able to detect `snap` by reading the content of script but it requires extra file-reading. Thus, we will always create Snapd-compatible tmpfile for `--allow-local-files` option if used CLI in Linux. A tmpfile will always be placed to home directory.
Fix #201 again.

Fix regression in --allow-local-files option with Snapd Chromium

---

CHANGELOG.md
README.md
src/converter.ts
src/preview.ts
src/utils/edge-finder.ts
src/utils/puppeteer.ts
src/utils/wsl.ts
test/utils/edge-finder.ts
test/utils/puppeteer.ts
test/utils/wsl.ts

Marp CLI will find out the executable path of Microsoft Edge for exporting slide deck into PDF, PPTX, and images if not found out Google Chrome and Chromium via `chrome-launcher` module. Chromium-based Edge is generally pre-installed to Windows 10 so Marp CLI users in Windows do no longer need to install extra Chrome browser just for exporting PDF.
Unlike Google Chrome, Microsoft is not to provide a reusable module for resolving executable path of Edge. But we can refer to the code of [Edge tools for VS Code](https://github.com/microsoft/vscode-edge-devtools/blob/c0da3de89df6ea363fc5fc43bc1489bd0d7cea95/src/utils.ts#L494-L524). It also has made by Microsoft so its logic is sufficiently reliable.
I implemented an original Edge finder similar to [Chrome finder by …

Fallback to Microsoft Edge if not installed Chrome / Chromium

---

CHANGELOG.md
src/converter.ts
src/preview.ts
src/templates/index.ts

Original report: marp-team/marp-vscode#175
Set `printable` flag to each templates, and fallback into `bare` template if tried Puppeteer conversion in not-printable template.
We've found sometimes background images using `![bg]()` are not rendered in PDF if using bespoke template and Chrome >= 85. I've recognized this problem as a regression by Chromium, and we should take this workaround until Chrome was fixed.
We could have taken to always use bare template in Puppeteer required conversion, but we have a mid term plan for the new printable handout template (#261) so `printable` flag is smart solution to keep multiple printable templates.
(Probably) we can close #293.

Mark bespoke template as not-printable and apply fallback if Puppeteer is required in bespoke template

---

README.md

An update of [Scoop's main bucket](https://github.com/ScoopInstaller/Main) is almost automated so reflected a bumped CLI version at least in a day. On the other hand, Chocolatey requires some days to reflect the latest because of [the handmade package](https://github.com/zverev-iv/choco-marp-cli).
**Marp team is always making importance to the security.** This PR will change the first option of Windows package manager to Scoop because we must prefer a choice for delivering the latest version rapidly.

Update README.md to prefer Scoop package manager

---

CHANGELOG.md
src/converter.ts
src/preview.ts
src/utils/puppeteer.ts

Apply workaround for Apple M1 by patching to `os.arch()`.
The current Puppeteer will override custom Chrome path when running on arm64: https://github.com/puppeteer/puppeteer/issues/6634
Test cases with Apple M1 have become all green.

Patch os.arch() to fix Puppeteer issue on Apple M1

---

CHANGELOG.md
src/utils/edge-finder.ts
test/utils/edge-finder.ts

Now the fallback to Microsoft Edge supports Linux binary. Marp CLI will find out the executable path from following if Linux is not running on WSL.
-  `/opt/microsoft/msedge-canary/msedge`
- `/opt/microsoft/msedge-dev/msedge`
- `/opt/microsoft/msedge-beta/msedge`
- `/opt/microsoft/msedge/msedge`
Resolves #296.

Add fallback to Microsoft Edge for Linux

---

CHANGELOG.md
src/marp-cli.ts
src/utils/puppeteer.ts
test/index.ts

Marp CLI's API interface on Marp for VS Code is requiring restart of VS Code after changed the custom Chrome path because of cached executable path.
This PR makes to reset cached path  every time when calling API interface.

Reset cached executable Chrome path if using Marp CLI through API interface

---

CHANGELOG.md
src/error.ts
src/utils/puppeteer.ts

If the shell environment is working in restricted by snap app (enabled AppArmor), Marp CLI may not spawn Chromium through installed from Snap store. (#287)
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753
This PR will throw better error spawning snap Chromium from the restricted shell environment, such as another snap app. This is useful to show warning in the combination of snap version of VS Code + Marp for VS Code.

Throw better error when spawning snap Chromium from another snap app

---

CHANGELOG.md
Dockerfile

Marp CLI official docker image has many international fonts (#26). But [the latest build has broken `font-ipa` font for Japanese](https://app.circleci.com/pipelines/github/marp-team/marp-cli/486/workflows/bfb69491-2512-490f-be40-a74a60a76045/jobs/3774).
Thus, I've updated Dockerfile to install Noto Sans CJK instead of broken `font-ipa` and existing Chinese font `wqy-zenhei`. It includes Chinese, Japanese, and Korean fonts.

Use Noto CJK font instead of broken font-ipa in Docker image

---

.circleci/config.yml
.github/workflows/test-win.yml
CHANGELOG.md
README.md

It's time to rename `master` branch to `main`! Updated images and workflows that have referenced to `master` branch.

Rename master branch to main

---

CHANGELOG.md
src/templates/bespoke/bespoke.ts
src/templates/bespoke/presenter/next-view.ts
src/templates/bespoke/sync.ts
src/templates/bespoke/utils.ts
test/templates/bespoke.ts

[Back/forward cache](https://web.dev/bfcache/) (a.k.a bfcache) is the browser optimization for enabling instant back and forward navigation. Firefox and Safari have enabled while a long time, and recently it has added to Chrome for mobile.
Marp CLI's bespoke template has disabled bfcache by adding `unload` event. So I refactored some bespoke plugins to use new Page Lifecycle API. A notable change is in sync plugin: Persist sync key between navigation, through history state instead of URL query parameter.
By this change, the slide HTML can get a 100% Lighthouse Best Practice score.

Optimize bespoke template for bfcache

---

CHANGELOG.md
jest.config.js
package.json
src/config.ts
src/converter.ts
src/file.ts
src/marp-cli.ts
test/converter.ts
test/index.ts
yarn.lock

Allow setting custom URL for `href` attribute of `<base>` element in the template. By this change, Marp CLI can refer to the other server for resources while Puppeteer conversion.
For example, we may provide more secure conversion without using `--allow-local-files` flag by creating localhost proxy server referring restricted local resources. In the case of Marp for VS Code, it might be able to provide PDF conversion support in the virtual workspace. (marp-team/marp-vscode#224)
> :warning: This option is currently internal setting for collaboration with Marp  for VS Code. **It is not intended using by the consumer and the result of conversion may break if set wrong base URL.**

Allow overriding base url through `baseUrl` option

---

README.md

Chocolately repository is not maintained actively: https://github.com/zverev-iv/choco-marp-cli/issues/13
Marp team is thinking user's security first, and the latest version has included some vulneribillity fixes. _We must not recommend a way to install for vulnerable outdated version in README._

Hide Chocolately repository from README.md

---

package.json
src/config.ts
src/file.ts
src/server.ts
src/templates/index.ts
src/theme.ts
test/__mocks__/express.ts
test/__mocks__/fs.ts
test/server.ts

- Use `fs.promises` functions instead of promisified functions. Node 12 no longer output experimental warning.
- Remove `mkdirp` module and use `fs.mkdir` with `recursive: true` option.
- Cover not tested codes to deal with coverage warning from codecov.

Refactor for Node 12

---

CHANGELOG.md
README.md

Do you remember [the (outdated) Marp app had been able to install by `brew install marp --cask`](https://github.com/yhatt/marp/tree/ae6dffad7dde68f10936a68a18622c211c143777#install) until 2019? Now Marp is getting back to Homebrew! 🎉 
We have confirmed the contribution to Homebrew formula in homebrew/homebrew-core#77702 so added installation guide for macOS Homebrew.
- Chocolatey package (#263) is seems no longer maintained so we've completely removed from README.md: https://github.com/zverev-iv/choco-marp-cli/issues/13.

Add installation guide for Homebrew

---

README.md

Signed-off-by: John Levon <levon@movementarian.org>

mention Node.js >= 12 requirement in README

---

CHANGELOG.md
README.md
package.json
rollup.config.js
yarn.lock

Fix remaining `node:` schema (used by the latest globby v12: #365) in `require()`, that there are in the result of build.

Add `@rollup/plugin-alias` to remove `node:` schema from `require` statements

---

README.md

I had to dig through issues to find out if I can use brave to do the conversion as it is a chromium-based browser. Adding this information to the README would be nice!
Based on https://github.com/marp-team/marp-cli/issues/333#issuecomment-810557264, we can use the `CHROME_PATH` variable to use other chromium-based browsers for conversion.

Add CHROME_PATH environment variable to README

---

README.md
package.json
src/config.ts
src/converter.ts
src/marp-cli.ts
test/_files/3.markdown
test/converter.ts
test/marp-cli.ts
yarn.lock

* Set `title` and `description` metadata to PDF
* Add presenter notes to PDF as annotations (if enabled `--pdf-notes` option)
```markdown
---
title: PDF metadata and annotations
description: By using pdf-lib, an outputted PDF has better metadata.
theme: uncover
---
By using pdf-lib, an outputted PDF has better metadata.
By setting `--pdf-notes` option, presenter notes can add to PDF as annotations.
```
```
marp slide.md --pdf --pdf-notes
```
Check out [meta.pdf](https://github.com/marp-team/marp-cli/files/6949207/meta.pdf).
Now in progress of #261 and #367. Author and keywords metadata are going to be added by another PR.

Apply metadata and presenter notes to PDF

---

CHANGELOG.md
README.md
src/config.ts
src/converter.ts
src/engine/info-plugin.ts
src/engine/meta-plugin.ts
src/marp-cli.ts
src/templates/index.ts
src/templates/layout.pug
test/converter.ts

Added `author` and `keywords` global directives and CLI options for setting metadata in the conversion output.
```markdown
---
author: Yuki Hattori
keywords: marp,marp-slide,marp-cli
---
```
- `author`: Set the name who made the slide deck. It is available in HTML, PDF, and PPTX.
- `keywords`: Set comma-separated keywords for the slide deck. It is available in HTML and PDF.
- In HTML, it can set `<meta name="keywords">` tag. However, it is known as [no longer used by Google since 2009](https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag). Don't expect improvement of SEO by setting keywords.
- In PDF, keywords will store to PDF metadata by turning into semicolon-separated keywords, that is the best practice of PDF keywords. e.g. `marp,slide,marp-cli` -> …

Add `author` and `keywords` directives and CLI options for setting metadata

---

CHANGELOG.md
src/converter.ts

When trying Puppeteer-based conversion in Linux, Marp CLI will create HTML tmpfile into a home directory instead of `/tmp`. It is important because Chromium that is installed through snap cannot read a local file from `/tmp` by a snap container confinement. (https://github.com/marp-team/marp-cli/issues/201#issuecomment-586725940)
However, I've found this behavior will break a workflow on Docker with `MARP_USER` env. Marp CLI image does not know about a specified user so `os.homedir()` will return a path that has no permissions for reading files by Chrome.
Thus, I changed to create HTML tmpfile into `/tmp` when used an official Docker image. Fix #360.

Create HTML for Puppeteer-based conversion in Docker into /tmp instead of home directory

---

CHANGELOG.md
README.md
src/config.ts
src/converter.ts
src/engine.ts
src/templates/index.ts
src/version.ts
test/converter.ts
test/engine.ts
test/marp-cli.ts

Improved a functional engine to allow using built-in Marp Core instance by non enumerable `marp` getter. Importing Marp Core installed by user is no longer required for simple customization.
```javascript
// engine.js
const { Marp } = require('@marp-team/marp-core')
const markdownItMark = require('markdown-it-mark')
module.exports = (opts) => new Marp(opts).use(markdownItMark)
```
```bash
npm install @marp-team/marp-core markdown-it-mark --save-dev
marp --engine ./engine.js slide-deck.md
```
```javascript
// engine.js
module.exports = ({ marp }) => marp.use(require('markdown-it-mark'))
```
```bash
npm install markdown-it-mark --save-dev
marp --engine ./engine.js slide-deck.md
```
A previous way is still available and useful for full-customization.
---
In addition, importing Marp Core has …

Expose Marp Core instance to functional engine

---

CHANGELOG.md
src/utils/puppeteer.ts

The Chrome finder by `chrome-launcher` will reject with an error instance containing a message to require setting `CHROME_PATH` env if rejected. Marp CLI has been outputted this error as warning immediately, but it just brings confusion if the user still had a compatible fallback such as Microsoft Edge.

Prevent outputting a warning about CHROME_PATH if fallbacked to Edge

---

CHANGELOG.md
src/utils/puppeteer.ts
test/utils/_executable_mocks/shebang-chromium
test/utils/_executable_mocks/shebang-snapd-chromium
test/utils/puppeteer.ts

If failed to connect to Chromium with pipe option with a known error (`Target.setDiscoverTargets`), Marp CLI will retry to spawn chromium with using WebSockets instead (`pipe: false`).
It might mitigate some conversion issues reported in marp-team/marp#165 and marp-team/marp#198. Close #395.
> This PR is also including refactor for #317. The warning had no longer  outputted in the snap binary that was installed by `apt` due to the shebang script for proxy.

Retry spawning Chromium with WebSocket connection if failed to connect through pipe

---

.circleci/config.yml
CHANGELOG.md
Dockerfile

By added multi-arch support for Docker image (#328), CI build has made flaky due to much slower build in emulated ARM architecture.
This PR will update Dockerfile to split build phase into multi-staged. Docker Buildx, that is using in CI now, can run multi-stage build in concurrency. This may be expected getting an improved build stability.

Update Dockerfile to split build into multi-stages

---

.circleci/config.yml
.dockerignore
CHANGELOG.md
Dockerfile

#401 has not improved the build time for multi-arch image. Thus, I've implemented the second approach: Build source code in CI, and `docker build` just copies the pre-built outputs.
It can remove a build phase in `Dockerfile` so make faster publishing updated Docker image.

Update Dockerfile to copy pre-built code in `/lib` into image

---

CHANGELOG.md
src/config.ts
src/converter.ts
test/converter.ts
test/marp-cli.ts

Allowed set timeout for Puppeteer by `PUPPETEER_TIMEOUT` env.
```
PUPPETEER_TIMEOUT=60000 marp --pdf large-markdown.md
```
By this setting, every actions by `puppeteer-core` (such as launching Chrome, page navigation, and PDF creation) will be timed out in 60 seconds. The default is 30s.
`PUPPETEER_TIMEOUT=0` means every actions will never be timed out.
> This option is maken assuming that it is used for debug a trouble while converting like https://github.com/marp-team/marp/discussions/225, so this setting cannot modify by CLI option and configuration file.

Allow to set timeout for Puppeteer actions by `PUPPETEER_TIMEOUT` env

---

CHANGELOG.md
src/utils/chrome-finder.ts
src/utils/edge-finder.ts
src/utils/puppeteer.ts
src/utils/wsl.ts
test/utils/wsl.ts

Improved WSL2 detection by using multiple heuristics.
Marp CLI will find out the browser for PDF/PPTX/image conversion automatically from the host OS (Windows). It works in WSL 1 but Puppeteer in WSL 2 cannot communicate with the browser spawned in the host OS.
I've updated `isWSL()` utility method for more reliable WSL 2 detection. We have no longer resolved Puppeteer from the host OS if WSL 2 was detected.
WSL2 detection is based on multiple heuristics on WSL environment:
- If there are both of `WSL_DISTRO_NAME` and `WSL_INTEROP` environment values.
- Else if the string of `/proc/version` is including `Microsoft-Standard-WSL2`.
- Else if it shows that the kernel was compiled by GCC v8 and later versions.
Related to marp-team/marp#113, and may resolve marp-team/marp#247.

Improved WSL 2 detection and browser resolution

---

CHANGELOG.md
src/marp-cli.ts
test/marp-cli.ts

In every following cases that have omitted image type, Marp CLI automatically chooses image(s) conversion for PNG:
```
marp test.md --image
marp --image -- test.md
marp --image --html test.md
marp test.md --images
marp --images -- test.md
marp --images --html test.md
```

Set `png` as the default type for CLI image options

---

.circleci/config.yml
.github/workflows/test-win.yml

The latest Codecov uploader will miss some of coverage outputs. https://github.com/codecov/uploader/issues/614

Downgrade Codecov uploader from latest to v0.1.15

---

CHANGELOG.md
src/engine/transition-plugin.ts
src/templates/bespoke/transition.ts
test/converter.ts

Updated experimental transition to make slide transitions configurable through `transition` local directive.
`transition` directive now allows YAML object. A previous way like `` is still able to use, but YAML object is useful to specify custom duration and delay.
- `type` **(required)**: The transition type.
- `duration` (optional): Set the duration of the transition in milliseconds between 0 to 5000.
- `delay` (optional): Set the delay to start the transition in milliseconds between 0 to 5000.
```yaml
transition:
type: fade
duration: 750
delay: 250
```
For better user experience, Marp CLI supports both of `ms` and `s` unit in `duration` and `delay`.
```yaml
transition:
type: fade
duration: 0.75s
delay: 250ms
```

[Experimental] Make transition configurable

---

README.md
src/config.ts
src/converter.ts
src/marp-cli.ts
test/converter.ts

add notes export option

---

src/templates/bespoke/bespoke.scss
src/templates/bespoke/presenter/presenter-view.tsx
test/templates/bespoke.ts

implement a timer in the presenter view

---

src/templates/bespoke/bespoke.scss
src/templates/bespoke/presenter/presenter-view.tsx
test/templates/bespoke.ts

with lots of notes this the presenter view can be difficult to use
this allows the area to be resized

allow the presenter view to be resized

---

CHANGELOG.md
README.md
src/converter.ts
src/marp-cli.ts
src/server.ts
test/converter.ts
test/server.ts

Follow up for `--notes` option

---

.eslintrc.js
CHANGELOG.md
src/file.ts
src/server/server-index.ts
src/templates/bespoke/navigation.ts
test/__mocks__/mkdirp.ts
test/converter.ts
test/marp-cli.ts
test/server/server-index.ts
test/theme.ts
test/watcher.ts

In the platform that allows to save the file into the root by default (Windows), `fs.mkdir` with recursive option to the drive root would fail by the permission error `EPERM`.
I've updated `File` class to prevent calling mkdirp if the output directory is the root.
Fix #442.

Prevent recursive mkdir to the root path while saving

---

README.md

If you copy and paste this as is and run marp, the output directory will be strange.

Remove unnecessary spaces in package.json in README.md

---

CHANGELOG.md
package.json
yarn.lock

This is meaning a hot patch to fix #445. So it does not include any update for devDependencies except a patch for vulnerability.
- Marp Core has bumped to [v2.4.2](https://github.com/marp-team/marp-core/releases/tag/v2.4.2).
- Make compatible with a patched markdown-it-emoji
- puppeteer-core has bumped to v13.6.0.
- Fix reported vulnerability in async module used by portfinder.

Upgrade dependencies to the latest version

---

CHANGELOG.md
src/utils/puppeteer.ts

Added `--test-type` flag as the default flag for Chromium launched by Puppeteer.
- Windows: Hide a information bar "You are using an unsupported command-line flag". Fix #453.
- macOS: Improve focus handling on the first interaction to the opened preview window.
- CI test: `--test-type` may bring reducing flaky tests in Windows environment.
See also: https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#test--debugging-flags:~:text=extension%20background%20pages.-,%2D%2Dtest%2Dtype,-%3A%20Basically%20the%202014

Add `--test-type` flag to the default Puppeteer launch arguments

---

.stylelintrc.yml
CHANGELOG.md
src/templates/bespoke/_transition.scss
src/templates/bespoke/bespoke.scss
src/templates/bespoke/transition.ts
src/templates/bespoke/utils/transition.ts

- Following up the latest spec of API
- `setElement` has removed from JavaScript API. https://github.com/WICG/shared-element-transitions/commit/0f7e52a92e96a492f7117bb6d9b6bc342b389daa
* Make resilience from API error
- If there were duplicated `page-transition-tag` by the custom CSS, the slide had been not navigatable by failure of `DocumentTransition.prototype.start`. When caught an error while running `page.start()`, we will fallback to the regular navigation.
- Update the base style for transition with shared elements.
- General cross-fading animation is set also to transition tags declared by users. It allows transition with the shared elements, just like PowerPoint's Morph and Keynote's Magic Move!
```markdown
---
marp: true
theme: gaia
_class: lead
transition: slide 1s
style: | …
```

[Transition experiment] Follow up the latest spec of API

---

CHANGELOG.md
src/engine/transition-plugin.ts
src/templates/bespoke/transition.ts
src/templates/bespoke/utils/transition.ts
test/converter.ts

#447
A built-in transition plugin for Marpit will recognize [metadata about keyframe scoping](https://github.com/marp-team/marpit/blob/77bead6f1915e16a773f0c343224d7a2925d949e/src/markdown/style/assign.js#L111) during parse, and rewrite the transition name into the scoped keyframe.
By this change, the Markdown author can declare or override the custom transitions that are available only in the current slide page.

[Transition experiment] Support custom transition declared in `<style scoped>`

---

CHANGELOG.md
src/templates/bespoke/transition.ts
src/templates/bespoke/utils/transition.ts
test/templates/bespoke.ts

Allowed setting the default duration time of animation for specific custom transition. Declare `--marp-transition-duration` custom property in the first keyframe (`from` or `0%`).
```css
@keyframes marp-incoming-transition-triangle {
from {
/* Set the default duration time of "triangle" transition to 1s. */
--marp-transition-duration: 1s;
clip-path: polygon(0% 0%, 0% 0%, 0% 0%);
}
to {
clip-path: polygon(0% 0%, 200% 0%, 0% 200%);
}
}
@keyframes marp-incoming-transition-backward-triangle {
from {
/* The duration defined in a forwarding animation will be used in backward animation too. */
/* A transition author also can set an individual default value to the backward transition. */
/* --marp-transition-duration: 2.5s; */
clip-path: polygon(100% 100%, 100% 100%, 100% 100%);
}
to {
clip-path: …
```

Allow setting default duration in custom transition

---

Dockerfile

This allows you to easily use the container image in CI where you would do some non-MARP operations before you invoke the CLI, without having to use the absolute path to the executable.
An example can be found [here](https://gitlab.com/just-ci/templates/-/merge_requests/68/diffs)

Add to PATH

---

CHANGELOG.md
src/utils/puppeteer.ts
test/utils/puppeteer.ts

By defining `CHROME_LAYOUTNG_PRINTING` env, Marp CLI will enable blink features `LayoutNGPrinting` and `LayoutNGTableFragmentation` to allow using [LayoutNG](https://www.chromium.org/blink/layoutng/) while printing for PDF conversion.
https://bugs.chromium.org/p/chromium/issues/detail?id=1121942
```sh
CHROME_LAYOUTNG_PRINTING=1 marp ./markdown.md --pdf
```
`LayoutNGTableFragmentation` is useful to deal with weird rendering of cropped table. (Reported in marp-team/marp-vscode#330)
It's still in development so we provide as opt-in feature through environment value.

Allow enabling LayoutNG while PDF conversion via CHROME_LAYOUTNG_PRINTING env

---

CHANGELOG.md
README.md
src/utils/puppeteer.ts
test/utils/puppeteer.ts

Don't suggest to install Chromium in error message if the current platform cannot resolve Chromium by `chrome-launcher` module

---

Dockerfile

This mirror appears to be down, causing the image to fail installing extra packages. Building the image will also fail now.
This changes it to use the cdn, selecting the best mirror (in theory ;-) ) for anyone building the image or adding packages.

fix: use cdn instead of specific mirror

---

.github/workflows/test-win.yml

- Replaced a deprecated `set-output` syntax.
- Update Codecov action to use v3.

Update GitHub Actions for testing on Windows

---

CHANGELOG.md
package.json
src/engine.ts
src/preview.ts
src/templates/bespoke/utils/transition.ts
src/utils/chrome-finder.ts
src/utils/puppeteer.ts
test/preview.ts
test/utils/puppeteer.ts
yarn.lock

The latest Puppeteer allows `headless: 'new'` option to use more compatible browser rendering that is same as the headful mode.
https://developer.chrome.com/articles/new-headless/
For the time being at least, Marp CLI can unlock the new headless mode an environment value `PUPPETEER_HEADLESS_MODE=new`.
```bash
PUPPETEER_HEADLESS_MODE=new marp ./new-headless.md --pdf
```
> If it became stable, we will change the default headless mode to `new`. If so, users would need to opt-in for using legacy headless mode via `PUPPETEER_HEADLESS_MODE=old`.

Support Puppeteer's new headless mode by `PUPPETEER_HEADLESS_MODE=new` env

---

CHANGELOG.md
jest.setup.js
package.json
src/templates/bespoke/state.ts
test/_browser/viewTransition.ts
test/templates/bespoke.ts
yarn.lock

`bespoke` template has become to support links for the stable anchor that has assigned to the element in the slide content. (e.g. Slugified Markdown headings, supported by Marp Core v3.6.0)
By this PR, users can jump to the slide page based on contents even if not used a link to the page number such as `[](#3)`.
```markdown
[Jump to Hello](#hello)
---
- ...
- ...
---
Example
```
In general Markdown document, a link of "Jump to Hello" can actually jump to "Hello" heading. By the change in this PR, the HTML with `bespoke` template also can jump to the slide page 3.
```markdown
[Jump to closing slide](#closing-slide)
---
...
---
<a name="closing-slide"></a>
Thanks!
```
`bespoke` template also supports the anchor defined through `<a name="..."></a>`. It's useful when there is not any Markdown …

Support stable anchor links in `bespoke` template

---

.circleci/config.yml
CHANGELOG.md
src/converter.ts
src/engine/directive-plugin.ts
test/converter.ts

Fixed #511.
The converter is now using Marpit plugin instead of a simple string injection to override CLI specific global directives.
This change will fix a failure about overriding global directives when `--html` option was enabled and there was a HTML block at the end of Markdown file.

Fix an edge case about failure of global directive injection by CLI with `--html` option

---

CHANGELOG.md
README.md
package.json
src/engine.ts
test/engine.ts
test/marp-cli.ts
yarn.lock

Marp CLI is using Vercel's [pkg](https://github.com/vercel/pkg) to build standalone binaries. However, it still cannot use ESM resolution via `import()`. Marp CLI v3.0.0 has supported ESM engine, but the standalone binary has been reported failing execution when trying to resolve an integrated Marp Core via `import()` due to lacked ESM support of pkg.
Not only pkg, alternative ways to make a binary also not supported ESM for now: [nexe](https://github.com/nexe/nexe), [the single executable application (Node.js 20)](https://nodejs.org/api/single-executable-applications.html))
So we currently have to disable ESM resolution in the binary packaged by pkg, and must revert to the same way as v2 (using `import-from`). If tried to resolve ESM in the standalone binary, Marp CLI fails with …

Temporarily disable ESM engine resolution when using the standalone binary

---

src/marp-cli.ts
test/marp-cli.ts

Hi marp team,
I'd like to suggest to route `--help` messages to stdout instead of stderr so that `marp --help | less` works. This is recommended by the [Gnu Coding Standards on --help](http://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html).
I appreciate you to develop and maintain such a great tool.:smile:
Thanks

Route help messages to stdout instead of stderr

---

CHANGELOG.md
README.md
jest.config.js
package.json
src/config.ts
src/converter.ts
src/engine.ts
src/index.ts
test/__mocks__/cosmiconfig.ts
test/_configs/esm-project/marp.config.js
test/_configs/esm-project/package.json
test/_configs/mjs/config.mjs
test/marp-cli.ts
yarn.lock

Updated cosmiconfig to the latest version, and supported ES Modules in the configuration file.
```javascript
// marp.config.mjs
export default {
allowLocalFiles: true,
html: true,
engine: ({ marp }) => marp.use(somePlugin)
}
```
Jest and pkg are not yet supported ES Modules due to the segmentation fault when running dynamic import `import()`. :(
- In Jest, we set up to transpile config files for testing into CommonJS manually.
- For the standalone binary powered by pkg, we are still disabling ESM import as same as #525.
---
This PR is also including another improvement for the config: Export `Config` type to allow better experience while writing a config in IDE. `@type` JSDoc annotation is available in both of CommonJS and ES Modules.
```javascript
/** @type …
```

ES Modules for the configuration file

---

Dockerfile

Now `harfbuzz` has a major update v8. I discovered installing it into docker image breaks PDF generation.
I don't know why installed harfbuzz into Docker image, but currently seems to be not required.
This may resolve #538.

Don't install the latest harfbuzz to Docker image

---

src/converter.ts

Related to discussion https://github.com/orgs/marp-team/discussions/466
The whole context is async already, but the `engine.render` method is not treated as possibly async.
Using `await` here allows to use either non-async and async render method, which is helpful for custom engines.

Allow async engine.render in converter

---

CHANGELOG.md
README.md
src/index.ts
test/__mocks__/cosmiconfig.ts
test/_configs/typescript/marp.config.ts
test/marp-cli.ts

The updated `cosmiconfig` in #548 has supported for TypeScript configuration file like `marp.config.ts`.

`marp.config.ts` support and `defineConfig` helper

---

CHANGELOG.md
src/utils/puppeteer.ts
test/utils/puppeteer.ts

- Make opt-outable Chrome sandbox by `CHROME_NO_SANDBOX` env
- It has designed to become a clear workaround for #543.
* Review arguments for obsolete Chromium versions
- `--disable-features=VizDisplayCompositor` for CI and container may be no longer required.

Review Puppeteer launch args

---

CHANGELOG.md
src/converter.ts

In a huge Markdown document, the encoded slide HTML may reach to the limit of data URI length.
I updated how to render a HTML for conversion to use [Puppeteer's `Page.setContent()`](https://pptr.dev/api/puppeteer.page.setcontent). Resolves #545.
> `about:`, the scheme of the default page `about:blank` after `browser.newPage()` is Chrome internal scheme, so it may be insecure because `about:` can access to some Chrome-internal resources provided by other `about:` pages. We should keep a secure scheme `data:` by going to the empty HTML page `data:text/html,` before rendering HTML through `Page.setContent()`.

Render HTML via `Page.setContent()` instead of data URI

---

CHANGELOG.md
src/preview.ts

By the same reason as #545, the preview for the result in memory fails in a large output. Changed to use `blob://` URL generated from the buffer for previewing.

Improve in-memory preview for a large content

---

.eslintrc.js
CHANGELOG.md
jest.setup.js
src/cli.ts

When used ANSI color to both of the text color and background, the content may be inaccessible color depending on the terminal theme choosed by the user. If the terminal was supported 256 colors and more, Marp CLI tries to use a specific color instead of ANSI colors. If not, fallback to simple color inverse `ESC[48m`.
Fix #552.

Accessibility: Render CLI's kind output in a specific color instead of ANSI color

---

CHANGELOG.md
src/converter.ts
src/engine/info-plugin.ts
src/templates/index.ts
test/converter.ts

`lang` directive has added since [Marpit framework v2.6.0](https://github.com/marp-team/marpit/releases/tag/v2.6.0). (https://github.com/marp-team/marpit/pull/376)
By this change, `lang` attribute in `<html>` element of templates will determine with the priority in order of below:
- If `lang` global directive was defined in Markdown, it would be set as `lang` attribute of `<html>`.
- If not, `lang` prefers the engine constructor option passed by `options` in configuration file.
- If `options.lang` is not defined, `lang` field of configuration file will be used. (Already implemented)
- If not defined `lang` field, Marp CLI will fallback to OS locale. This is the most general case for now. (Already implemented)
Closes #542.

Reflect `lang` global directive to HTML templates

---

.circleci/config.yml
.github/workflows/test-win.yml
CHANGELOG.md

Node.js LTS now becomes v20. Added CI testing against Node.js v20.

Added CI testing against Node.js v20

---

CHANGELOG.md
src/utils/puppeteer.ts
test/utils/puppeteer.ts

Marp CLI is using the classic headless known as `shell` mode in current Puppeteer.
https://developer.chrome.com/blog/chrome-headless-shell
The headless shell will become to remove from the browser binary in the last of 2024, so we have to update the headless mode into the current. Marp CLI had been able to choose the new headless mode via `PUPPETEER_HEADLESS_MODE=new` env (#508), and now it will be used to revert into the classic headless `shell` via `PUPPETEER_HEADLESS_MODE=old`,`legacy`, or `shell`.

Adopt new headless mode by default

---

src/browser/browsers/chrome.ts
test/browser/browsers/chrome.ts

When the specified browser path is located in WSL host OS, `ChromeBrowser.createPuppeteerDataDir()` returns the Windows path even if Marp CLI is working on Linux. However, Puppeteer's `userDataDir` will always normalize the path by a manner of Linux.
So we stopped to use `userDataDir` option and pass the location of Chrome data dir through `args` option directly.

Change to pass the location of Chrome data dir through args directly

---

CHANGELOG.md
README.md
src/browser/browsers/chrome.ts
src/browser/finder.ts
src/browser/finders/edge.ts
src/config.ts
src/converter.ts
src/error.ts
src/marp-cli.ts
src/utils/__mocks__/yargs.ts
src/utils/wsl.ts
test/__mocks__/cosmiconfig.ts
test/__mocks__/express.ts
test/__mocks__/get-stdin.ts
test/__mocks__/wrap-ansi.ts
test/browser/browsers/chrome.ts
test/browser/finders/edge.ts
test/converter.ts
test/index.ts
test/marp-cli.ts
test/server.ts
test/utils/wsl.ts

Resolves #565.
This PR introduces new options about browser: `--browser`, `--browser-path`, `--browser-protocol`, and `--browser-timeout`.
```
Browser Options:
--browser           The kind of browser to use for PDF, PPTX, and image
conversion
[string] [choices: "auto", "chrome", "edge", "firefox"] [default: "auto"]
--browser-path      Path to the browser executable (Find automatically if
not set)                                      [string]
--browser-protocol  Preferred protocol to use for browser connection
[string] [choices: "cdp", "webdriver-bidi"] [default: "cdp"]
--browser-timeout   Timeout for each browser operation in seconds (0 to
disable)                                 [default: 30]
```
The `--browser` option specifies the kind of browser for conversion. If set comma-separated …

Add browser options `--browser` and several sub options

---

CHANGELOG.md
src/browser/browser.ts
src/browser/browsers/chrome.ts
src/browser/browsers/firefox.ts
src/browser/finders/chrome.ts
src/browser/finders/edge.ts
src/browser/finders/firefox.ts
src/converter.ts
src/utils/wsl.ts
test/browser/finders/chrome.ts
test/utils/wsl.ts

Marp CLI has been already supported out of the box conversion in WSL 1, but WSL 2 is not yet supported. (marp-team/marp#113) This PR introduces the out of the box conversion in WSL 2 with "mirrored network mode".
WSL 1 shares the network with Windows. Puppeteer can communicate with browser's remote debug that is binding to the localhost port. On the other hand, WSL 2 has a separated NAT network from Windows by default, so it is difficult to communicate WSL 2 with Windows.
If configured WSL 2 to enable "mirroed network mode", WSL 2 will become to share the network interface with Windows as same as WSL 1. In this mode, we have confirmed that Puppeteer for Chrome can communicate with the process on the Windows host.
```
[wsl2]
networkingMode=mirrored
```
Marp CLI's browser finder will become …

Find Chrome and Edge from the host Windows as fallback when WSL 2 is mirrored network mode

---

.circleci/config.yml
.dockerignore
.github/workflows/build-image.yml
CHANGELOG.md
Dockerfile
README.md
docker-entrypoint

Marp CLI v4 will introduce brand-new official container image:
- **Change base image from Alpine to Debian.** Puppeteer has several reports about timeout due to using Alpine Linux as a container: https://github.com/search?q=repo%3Apuppeteer%2Fpuppeteer+timeout+alpine&type=issues. We expect to fix [#592](https://github.com/marp-team/marp-cli/issues/592) by this change.
* **Revert Dockerfile to build Marp CLI from source in the build phase instead of using already built asset.** An original change had been introduced in [#402](https://github.com/marp-team/marp-cli/pull/402), but using multi-stage build with `--platform=$BUILDPLATFORM` is much better.
- **Publish the image into both of Docker Hub and GitHub Container Registry.** The image publishing workflow has been moved from CircleCI to …

Renew Docker image to change the base from Alpine to Debian slim, and publish also to GitHub Container Registry

---

.circleci/config.yml
CHANGELOG.md
package-lock.json
package.json
src/browser/browser.ts
src/browser/browsers/firefox.ts
src/converter.ts
src/file.ts
src/utils/jpeg.ts
src/utils/tmp.ts
test/converter.ts

Currently, WebDriver BiDi does not support image rendering except PNG. Since Marp CLI v4, `--image(s) jpeg` option may use `sharp` image processor when converting image to JPEG if used WebDriver BiDi.
However, sharp is too huge library just for usage of converting PNG to JPEG.
To diet the dependency, I've improved PNG to JPEG conversion to use the browser `<canvas>` through Puppeteer. By this change, the filesize of standalone binary will be reduced about 8MB.

Get rid of sharp dependency in favor of JPEG conversion via the browser

---

.circleci/config.yml
.github/workflows/test-win.yml
CHANGELOG.md
src/browser/browsers/chrome.ts
src/utils/container.ts

Fix #611.
In addition, this PR reverts that sandbox disabling ignores in CI environments.

Disable Chrome sandbox if running CLI as root

---

CHANGELOG.md
src/browser/browsers/chrome.ts
test/browser/browsers/chrome.ts

It has mainly designed to become the workaround of timeout error for Alpine 3.20: #592, #617
```bash
CHROME_DISABLE_GPU=1 marp --pdf markdown.md
```
However, I'm doubtful that `--disable-gpu` for Chrome will actually solve the problem.

Allow to disable GPU use of Chrome through `CHROME_DISABLE_GPU` environment variable

---

README.md

As described in #620, ~~homebrew package~~ has been built is for ARM only
> edited @yhatt: The standalone binary is ARM only, not homebrew.

Clarify supported architectures of standalone binary

---

CHANGELOG.md
src/preview.ts

When opening multiple previews with `--preview` option, the preview window detector will sometimes fail with the parse error of empty URL for `other` type page.
```
node:internal/url:818
href = bindingUrl.parse(input, base, true);
^
TypeError: Invalid URL
at new URL (node:internal/url:818:25)
at idMatcher (/Users/yhatt/Programs/marp/marp-cli/lib/marp-cli-DSmb16j_.js:25490:33)
at /Users/yhatt/Programs/marp/marp-cli/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
at Array.map (<anonymous>)
at Object.emit (/Users/yhatt/Programs/marp/marp-cli/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
at CdpBrowser.emit (/Users/yhatt/Programs/marp/marp-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
at #onAttachedToTarget …
```

Make the preview option stable against occasional invalid URL errors

---

.circleci/config.yml
.github/workflows/test-win.yml
CHANGELOG.md
README.md
src/browser/browser.ts
src/browser/manager.ts
src/config.ts
src/converter.ts
src/marp-cli.ts
src/utils/memoized-promise.ts
src/utils/wsl.ts
test/converter.ts
test/marp-cli.ts

This PR introduces `--parallel` / `-P` option to set the number of concurrency of parallel conversion for multiple files.
```bash
marp --parallel 5 ./marp-slides
```
By applying the robust async process (async initialization is running only once, and all of successors will wait that initialization) to browser operations, the parallel processing could be achieved in a simple queue and workers.
Marp CLI will use up to 5 workers while converting multiple files in the queue by default. If used Marp CLI for converting multiple Markdowns into PDF/PPTX/image(s), this setting will make drastically faster conversion than previous. CLI user can tweak the number of concurrency by using `--parallel` or `-P` option.
Resolves #509.
`marp-parallel` folder is including 30 empty Markdown files, and Marp …

Introduce parallelism for batch conversion: `--parallel` / `-P`

---

CHANGELOG.md
Dockerfile

This is effectively the retry of #148. Execute Marp CLI once while building container image, and create v8 precompiled cache.

Generate V8 compile cache when building container image

---

CHANGELOG.md
src/browser/manager.ts
src/soffice/finder.ts
src/soffice/soffice.ts
test/browser/manager.ts
test/soffice/finder.ts
test/soffice/soffice.ts

Follow up for experimental `--pptx-editable` option (#626), especially Windows environment.
- Removed Windows LibreOffice app transparency from WSL. WSL-specific finder is no longer used.
- Tmpfile saved into WSL environment cannot read from Windows LibreOffice.
- Detect LibreOffice installed via Scoop in Windows. (#631)
- Update error level of soffice stderr from ERROR to WARN.
- Windows may throw an error about libpng as ERROR, but the conversion would be successful. Showing ERROR level may lead confusion.

Follow up for experimental `--pptx-editable` in Windows environment

---

CHANGELOG.md
src/server.ts

Fix #633.
Update `Server#convertMarkdown` to return actually processed type instead of using the type stored in the class instance provided by the global context.

Fix returning wrong file extension in concurrent requests on server mode

---

.github/workflows/build-image.yml
CHANGELOG.md

Use arm64 hosted runner to build container image for ARM

---

src/server.ts
src/watcher.ts
test/watcher.ts

#664 had introduced circular dependency, and `npm run build` was getting warning from rollup.

Fix circular dependency warning

---

CHANGELOG.md
rollup.config.mjs
src/converter.ts
src/typings.d.ts
src/utils/pdf.ts

Fix #676.
The latest pptxgenjs has improved support for hybrid environments, such as Web, Node.js, and other bundlers. If pptxgenjs detected running on Node.js, pptxgenjs will try to import `node:fs` and `node:https` dynamically with `import` statement.
> ```typescript
> // STEP 2: Lazy-load Node built-ins if needed
> const loadNodeDeps = isNode
>   ? async () => {
>     ; ({ default: fs } = await import('node:fs')); ({ default: https } = await import('node:https'))
>   }
>   : async () => { }
> ```
>
> _&mdash; https://github.com/gitbrent/PptxGenJS/blob/3c9ec1b687c174952166f6a34b5e87ebf69fa469/src/gen-media.ts#L23_
However, a dyanamic `import` statement is known that it does not work as expected in the binary build packaged by `pkg` (`@yao-pkg/pkg`).
So I've updated the configuration of …

Avoid using dynamic `import()` in the bundled output as much as possible

---

.circleci/config.yml
.github/CONTRIBUTING.md
.github/workflows/test-win.yml
package-lock.json
package.json
patches/README.md

For making the process for preparing development simplify, add `prepare` script to run `patch-package` for `npm install` / `npm ci` (without arguments).
[patch-package](https://github.com/ds300/patch-package) recommend to run `patch-package` in `postinstall` hook, but it also triggers unnecessarily when installed Marp CLI by users, such as `npm i @marp-team/marp-cli --save`.
Marp CLI is currently using `patch-package` only for dev dependencies, so we have no need to run it in `postinstall` hook.

Add `prepare` hook script to run `patch-package`
